/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/conversations/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Import a conversation (voice file, transcript file, or pasted text)
         * @description Single entrance for all imported conversations. The router (worktree D)
         *     inspects the request, persists a ConversationArtifact + Meeting,
         *     and dispatches to the voice-ingest pipeline (worktree B) or the
         *     transcript-ingest pipeline (worktree C).
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "multipart/form-data": {
                        workspace_id: string;
                        title: string;
                        /**
                         * @default private
                         * @enum {string}
                         */
                        visibility?: "private" | "workspace" | "shared";
                        labels?: string[];
                        /**
                         * Format: binary
                         * @description Audio file. Use this OR transcript_file OR pasted_transcript.
                         */
                        voice_file?: string;
                        /** Format: binary */
                        transcript_file?: string;
                        pasted_transcript?: string;
                    };
                };
            };
            responses: {
                /** @description Accepted; processing begins asynchronously. */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ImportAccepted"];
                    };
                };
                /** @description Invalid input. Codes: no_input (zero body parts present), multiple_inputs (more than one body part present), invalid_format (unsupported file type). */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/meetings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List meetings for a workspace */
        get: {
            parameters: {
                query: {
                    workspace_id: string;
                    limit?: number;
                    offset?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            items: components["schemas"]["Meeting"][];
                            total: number;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/meetings/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a meeting record */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Meeting"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/meetings/{id}/transcript": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the normalized transcript for a meeting */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["NormalizedTranscript"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Meeting exists but transcript not yet ready. */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/memory-cards": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a memory card (draft)
         * @description Inserts a new MemoryCard in state `draft`. The server assigns
         *     `memory_card_id` and timestamps. Returns 404 if `meeting_id` is unknown.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["MemoryCardCreate"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MemoryCard"];
                    };
                };
                /** @description Meeting not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Validation error */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/meetings/{id}/memory-cards": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List memory cards for a meeting */
        get: {
            parameters: {
                query?: {
                    type?: "decision" | "action_item" | "pain_point" | "quote" | "requirement" | "risk" | "open_question" | "technical_detail";
                    state?: "candidate" | "draft" | "committed" | "rejected";
                    limit?: number;
                    offset?: number;
                };
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MemoryCardListResponse"];
                    };
                };
                /** @description Meeting not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/memory-cards/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Patch a draft memory card
         * @description Only allowed when state is `draft`. Whitelist of editable fields.
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["MemoryCardPatch"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MemoryCard"];
                    };
                };
                /** @description Card not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Illegal transition (card not in draft) */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["IllegalTransition"];
                    };
                };
                /** @description Validation error */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
    "/api/memory-cards/{id}/commit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Commit a draft memory card
         * @description Transitions `draft` → `committed`; clears `needs_review`.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MemoryCard"];
                    };
                };
                /** @description Card not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Illegal transition */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["IllegalTransition"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/memory-cards/{id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reject a draft memory card
         * @description Transitions `draft` → `rejected`; clears `needs_review`.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MemoryCard"];
                    };
                };
                /** @description Card not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Illegal transition */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["IllegalTransition"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/meetings/{id}/finalize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Finalize a meeting via Hermes
         * @description Runs `hermes_plugin.meeting_finalization`, persists returned cards as
         *     `draft` MemoryCards, marks the meeting `finalized`, and returns a summary.
         *     Synchronous in Phase 2; long-running calls block. For timestamped
         *     transcripts the plugin chunks the meeting into `chunk_minutes`-sized
         *     windows and runs one Claude pass per window so long meetings don't
         *     exceed the model context budget.
         */
        post: {
            parameters: {
                query?: {
                    /**
                     * @description Time-window size (in minutes) used by the chunked extractor.
                     *     Out-of-range values return 422. Untimestamped transcripts fall
                     *     back to single-pass finalization regardless of this value.
                     */
                    chunk_minutes?: number;
                };
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["FinalizeResponse"];
                    };
                };
                /** @description Meeting not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Meeting already finalized */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AlreadyFinalized"];
                    };
                };
                /** @description Hermes plugin unavailable */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HermesUnavailable"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/qa/meeting": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ask a question about a single meeting (Hermes-backed) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["QARequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["QAResponse"];
                    };
                };
                /** @description Meeting not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Validation error */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Hermes plugin unavailable */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HermesUnavailable"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ImportAccepted: {
            artifact_id: string;
            meeting_id: string;
            /**
             * @description At 202 time the artifact is always 'received'. Subsequent state transitions are observed via GET /api/meetings/{id}.
             * @enum {string}
             */
            processing_status: "received";
        };
        /** @description Mirrors schemas/meeting.schema.json */
        Meeting: {
            meeting_id: string;
            artifact_id: string;
            /** @default  */
            title: string;
            /** @enum {string} */
            status: "live" | "processing" | "ready" | "finalized" | "failed";
            /** Format: date-time */
            started_at?: string | null;
            /** Format: date-time */
            ended_at?: string | null;
            /** Format: date-time */
            finalized_at?: string | null;
            detected_pattern?: components["schemas"]["MeetingPattern"];
            current_schema?: Record<string, never> | null;
            /** @enum {string} */
            evidence_quality: "unknown" | "high" | "medium" | "low" | "lowest";
        };
        /** @description Mirrors schemas/meeting_pattern.schema.json */
        MeetingPattern: {
            primary_pattern: string;
            secondary_patterns?: string[];
            interaction_style?: string | null;
            confidence: number;
            reason?: string | null;
        };
        /** @description Mirrors schemas/normalized_transcript.schema.json */
        NormalizedTranscript: {
            meeting_id: string;
            segments: components["schemas"]["SpeakerSegment"][];
        };
        /** @description Mirrors schemas/speaker_segment.schema.json */
        SpeakerSegment: {
            segment_id: string;
            speaker_id?: string | null;
            speaker_name?: string | null;
            start_ms?: number | null;
            end_ms?: number | null;
            text: string;
            confidence?: number | null;
            /** @enum {string} */
            source_type: "live_voice" | "zoom_rtms" | "voice_file" | "transcript_file" | "pasted_transcript";
            is_final: boolean;
        };
        /** @description Mirrors schemas/memory_card.schema.json */
        MemoryCard: {
            memory_card_id: string;
            meeting_id: string;
            /** @enum {string} */
            state: "candidate" | "draft" | "committed" | "rejected";
            /** @enum {string} */
            type: "decision" | "action_item" | "pain_point" | "quote" | "requirement" | "risk" | "open_question" | "technical_detail";
            title: string;
            content: string;
            source_chunk_ids: string[];
            source_start_ms?: number | null;
            source_end_ms?: number | null;
            speakers_json?: string[] | null;
            confidence: number;
            /** @default true */
            needs_review: boolean | null;
            created_by_agent?: string | null;
            /** Format: date-time */
            created_at?: string | null;
            /** Format: date-time */
            updated_at?: string | null;
        };
        /** @description Request body for POST /api/memory-cards (also the per-card shape Hermes returns from meeting_finalization). */
        MemoryCardCreate: {
            meeting_id: string;
            /** @enum {string} */
            type: "decision" | "action_item" | "pain_point" | "quote" | "requirement" | "risk" | "open_question" | "technical_detail";
            title: string;
            content: string;
            source_chunk_ids: string[];
            source_start_ms?: number | null;
            source_end_ms?: number | null;
            speakers_json?: string[] | null;
            confidence: number;
            /** @default true */
            needs_review: boolean;
            created_by_agent?: string | null;
        };
        /** @description Partial update for a draft MemoryCard. Whitelist; state transitions go through commit/reject. */
        MemoryCardPatch: {
            /** @enum {string} */
            type?: "decision" | "action_item" | "pain_point" | "quote" | "requirement" | "risk" | "open_question" | "technical_detail";
            title?: string;
            content?: string;
            source_chunk_ids?: string[];
            source_start_ms?: number | null;
            source_end_ms?: number | null;
            speakers_json?: string[] | null;
            confidence?: number;
            needs_review?: boolean;
        };
        MemoryCardListResponse: {
            items: components["schemas"]["MemoryCard"][];
            total: number;
        };
        IllegalTransition: {
            error: {
                /** @enum {string} */
                code: "illegal_transition";
                from: string;
                to: string;
            };
        };
        AlreadyFinalized: {
            error: {
                /** @enum {string} */
                code: "already_finalized";
            };
        };
        HermesUnavailable: {
            error: {
                /** @enum {string} */
                code: "hermes_unavailable";
                message: string;
            };
        };
        FinalizeResponse: {
            meeting_id: string;
            /** Format: date-time */
            finalized_at: string;
            cards_created: number;
            summary: string;
            /**
             * @description Number of transcript chunks the chunked extractor processed.
             *     Defaults to 1 for the legacy single-pass finalization path.
             * @default 1
             */
            chunks_processed: number;
        };
        QARequest: {
            meeting_id: string;
            question: string;
        };
        QAEvidenceItem: {
            chunk_id: string;
            text: string;
            speaker?: string | null;
            start_ms?: number | null;
            end_ms?: number | null;
        };
        QAResponse: {
            answer: string;
            evidence: components["schemas"]["QAEvidenceItem"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
