/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/conversations/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Import a conversation (voice file, transcript file, or pasted text)
         * @description Single entrance for all imported conversations. The router (worktree D)
         *     inspects the request, persists a ConversationArtifact + Meeting,
         *     and dispatches to the voice-ingest pipeline (worktree B) or the
         *     transcript-ingest pipeline (worktree C).
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "multipart/form-data": {
                        workspace_id: string;
                        title: string;
                        /**
                         * @default private
                         * @enum {string}
                         */
                        visibility?: "private" | "workspace" | "shared";
                        labels?: string[];
                        /**
                         * Format: binary
                         * @description Audio file. Use this OR transcript_file OR pasted_transcript.
                         */
                        voice_file?: string;
                        /** Format: binary */
                        transcript_file?: string;
                        pasted_transcript?: string;
                    };
                };
            };
            responses: {
                /** @description Accepted; processing begins asynchronously. */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ImportAccepted"];
                    };
                };
                /** @description Invalid input. Codes: no_input (zero body parts present), multiple_inputs (more than one body part present), invalid_format (unsupported file type). */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/meetings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List meetings for a workspace */
        get: {
            parameters: {
                query: {
                    workspace_id: string;
                    limit?: number;
                    offset?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            items: components["schemas"]["Meeting"][];
                            total: number;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/meetings/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a meeting record */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Meeting"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/meetings/{id}/transcript": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the normalized transcript for a meeting */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["NormalizedTranscript"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Meeting exists but transcript not yet ready. */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ImportAccepted: {
            artifact_id: string;
            meeting_id: string;
            /**
             * @description At 202 time the artifact is always 'received'. Subsequent state transitions are observed via GET /api/meetings/{id}.
             * @enum {string}
             */
            processing_status: "received";
        };
        /** @description Mirrors schemas/meeting.schema.json */
        Meeting: {
            meeting_id: string;
            artifact_id: string;
            /** @default  */
            title: string;
            /** @enum {string} */
            status: "live" | "processing" | "ready" | "finalized" | "failed";
            /** Format: date-time */
            started_at?: string | null;
            /** Format: date-time */
            ended_at?: string | null;
            /** Format: date-time */
            finalized_at?: string | null;
            detected_pattern?: components["schemas"]["MeetingPattern"];
            current_schema?: Record<string, never> | null;
            /** @enum {string} */
            evidence_quality: "unknown" | "high" | "medium" | "low" | "lowest";
        };
        /** @description Mirrors schemas/meeting_pattern.schema.json */
        MeetingPattern: {
            primary_pattern: string;
            secondary_patterns?: string[];
            interaction_style?: string | null;
            confidence: number;
            reason?: string | null;
        };
        /** @description Mirrors schemas/normalized_transcript.schema.json */
        NormalizedTranscript: {
            meeting_id: string;
            segments: components["schemas"]["SpeakerSegment"][];
        };
        /** @description Mirrors schemas/speaker_segment.schema.json */
        SpeakerSegment: {
            segment_id: string;
            speaker_id?: string | null;
            speaker_name?: string | null;
            start_ms?: number | null;
            end_ms?: number | null;
            text: string;
            confidence?: number | null;
            /** @enum {string} */
            source_type: "live_voice" | "zoom_rtms" | "voice_file" | "transcript_file" | "pasted_transcript";
            is_final: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
